const fs = require('fs');
const path = require('path');
const { appDir, ensureDir } = require('./config');
const { logEvent, logLatency } = require('./log');
const { applyHubSessionPath, applyHubTurnContext, isActiveEnterprise, getActiveEnterpriseHooks } = require('./enterprise-plugin');

const MAX_RECENT_TURNS = 12;
const MAX_SUMMARY_BULLETS = 16;
const MAX_EXCERPT_CHARS = 220;
/** Cap inline session body in turn prompts (full session still on disk). */
const MAX_TURN_SESSION_CHARS = 6000;
/** Cap each pending mail body embedded in the turn prompt. */
const MAX_TURN_MAIL_CHARS = 8000;

function hubPromptDir(hub) {
  return path.join(appDir(hub), 'prompts');
}

function hubRuntimePromptFile(hub) {
  return path.join(hubPromptDir(hub), 'hub.md');
}

function hubTurnsDir(hub) {
  return path.join(hubPromptDir(hub), 'turns');
}

function hubSessionFile(hub, sessionOrUserId) {
  if (isActiveEnterprise()) {
    try {
      const p = applyHubSessionPath(hub, sessionOrUserId || null);
      if (p) return p;
    } catch (_err) {
      /* fall through */
    }
    // Default enterprise naming when hook absent but we have a user id
    const uid =
      typeof sessionOrUserId === 'string'
        ? sessionOrUserId
        : sessionOrUserId && (sessionOrUserId.user_id || sessionOrUserId.userId);
    if (uid) return path.join(appDir(hub), `hub-session-${uid}.md`);
  }
  return path.join(appDir(hub), 'hub-session.md');
}

function hubRuntimeCwd(hub) {
  return path.join(appDir(hub), 'runtime-cwd');
}

function extractAgentSections(agentText) {
  const start = agentText.search(/^## § 3\b/m);
  const end = agentText.search(/^## § 5\b/m);
  if (start === -1) throw new Error('AGENT.md is missing § 3');
  return agentText.slice(start, end === -1 ? agentText.length : end).trim();
}

/**
 * Slim always-on hub runtime prompt (Phase 1).
 * Fat detail (Knowledge Stack, journal schemas, Claude hook, nightly) is
 * on-demand via paths — open only when the turn needs it.
 * Session compaction is owned by the control plane; the LLM must not rewrite
 * hub-session.md.
 */
function deriveHubRuntimePrompt(hub) {
  const sessionRel = path.relative(hub, hubSessionFile(hub));
  const hubAbs = path.resolve(hub);
  return [
    '# BizAgent Hub Runtime Prompt',
    '',
    'Generated always-on runtime prompt (slim). Do not edit this file directly;',
    'edit control-plane/lib/hub-memory.js deriveHubRuntimePrompt or AGENT.md and regenerate.',
    '',
    '## Identity',
    '',
    'You are the **Products Team Lead** (PTL). You report to the operator (CEO).',
    'Hub-and-spoke: this repo is the hub; each product has one agent owning one or more project repos.',
    '`registry.json` is the source of truth. Use each product\'s `agent_name` when speaking to the operator;',
    'use slugs only in message file headers (`from:`, `to:`).',
    '',
    '## What is a "product"?',
    '',
    'If it matches gather → build → distribute, it can be a BizAgent product (not only software).',
    'BizAgent is a product-development OS — not search, not only a coding assistant. Details: `AGENT.md` / architecture.',
    '',
    '## System state (always true on runtime launches)',
    '',
    `- Hub root (absolute): \`${hubAbs}\``,
    '- The system is **BUILT**. `registry.json` exists. **Never** run setup/interview or §0 "detect state".',
    '- Do **not** re-read root `AGENT.md` for setup. Operational rules are in this prompt.',
    '',
    '## Non-negotiable limits',
    '',
    '1. You **NEVER** write code, edit project files, update sitemaps, or write journal entries for any product.',
    '2. You **NEVER** do work that belongs to a product agent — even if small or faster yourself.',
    '3. Operator task → identify owning agent by **agent_name** → message their inbox (`to:` slug) → wait for reply → report back.',
    '4. Do **not** start product implementation. If you already touched a product repo or `agents/<slug>/` for product work: stop, undo, delegate.',
    '5. **Hub machinery is user-gated.** By default do **not** edit `control-plane/`, the web UI, dispatch/auth, `templates/`, hub `scripts/` behavior, `cli.json`, or registry schema/shape.',
    '   Soft ops without a special ask: route/archive mail, hub journal tags, KS capture, read registry, delegate.',
    '6. **Hub code changes only when the operator explicitly requests** a hub/control-plane/UI/ops-code change. Then: minimal scoped diff, no speculative refactors, no drive-by cleanups.',
    '7. If hub machinery is wrecked: tell the operator to run `scripts/factory-reset.sh repair` from a shell (keeps registry/agents). Do not improvise a half-reset.',
    '',
    '## Brevity',
    '',
    'Replies to the operator default to **two sentences or less**. Longer only when the work requires it.',
    'Messages to product agents: only what the recipient needs to act — no preamble, recap, or signoff.',
    'Prefer one task per agent mail; include goal, constraints, and done-when so a cold product agent can act.',
    '',
    '## Channel rules (non-negotiable)',
    '',
    '- **Stdout is debug only.** Nothing you print is shown to the operator.',
    '- **Operator-visible text** must go through the reserved body file:\n  `RESERVED_REPLY_BODY` path is pre-created by the CP; hub writes markdown body only.',
    '- **Never** hand-write files under `outbox/` for operator replies (free-form outbox is **banned** for `to: user`).',
    '- Product-agent mail (to a slug) uses the write-message helper.',
    '- When an agent→hub message arrives, write **at most one** short user-visible summary. Never emit duplicate "X is done" notices.',
    '',
    '## This-turn order (outbox-first)',
    '',
    '1. **Answer first** via the mandatory write path (see Message delivery). Success = that write returns OK / the reserved body file is non-empty.',
    '2. **Then housekeep:** archive handled `inbox/*.md` into `inbox/archive/` immediately after acting on each. For agent→hub completion mail, write **at most one** summary to the operator even if the hub turn is re-launched before you archive; the inbox file name + body is the key. If a summary was already produced for this exact mail, just archive it.',
    '3. Session memory is **CP-owned** (see Runtime Memory). Do not rewrite or compress it.',
    '4. Only then: optional journal `[Maintenance]` / `[Company]` bullets if warranted.',
    '',
    '## Message delivery (mandatory write path)',
    '',
    '### Operator / console reply (`to: user`)',
    '',
    'When this turn has a `conversation_id`, prefer **one** of:',
    '',
    '1. **Reserved body file** (preferred when the turn prompt gives `RESERVED_REPLY_BODY`): write **only the markdown body** (no YAML frontmatter) to that absolute path with your file tool. The control plane wraps frontmatter and routes it.',
    '2. **write-message helper:**',
    '   ```bash',
    '   scripts/write-message.sh --to user --from hub --subject "short subject" \\',
    '     --conversation-id "<id from this turn>" --body "Your reply here."',
    '   ```',
    '',
    'Do **not** hand-write files under `outbox/`. Do **not** invent a `conversation_id`.',
    '',
    '### Product-agent mail',
    '',
    '```bash',
    'scripts/write-message.sh --to <slug> --from hub --subject "short subject" --body "..."',
    '```',
    '',
    '**Interim messages** only for unbounded delays (dispatch, URL fetch): brief write-message first, full reply second, same `conversation_id`. Skip interims for quick synthesis.',
    '',
    '### Deferred wake',
    '',
    '`scripts/defer.sh --to <slug|hub> --in 15m --body "…"` → inbox `kind: defer-wake`.',
    '',
    '## Runtime Memory (CP-owned)',
    '',
    `\`${sessionRel}\` is current session memory (rolling summary + recent turns). The control plane already compacted it.`,
    '**Read-only for you.** Do not compress, rewrite, or "keep compact" this file — the CP owns that.',
    'Use the **Pending mail** and **Session** sections of the turn prompt when provided; open the session file only if the turn prompt lacks what you need.',
    '',
    '## On-demand references (open only if this turn needs them)',
    '',
    '- Full setup/ops manual: `AGENT.md` (never for §0 detect-built on a live hub)',
    '- Knowledge Stack / weekly refresh: `WEEKLY.md`, `company/`, `knowledge-stack/`',
    '- **Library** (operator-facing plans/specs/reports): write under `library/` and keep `library/manifest.json` in sync — the operator browses these in the UI without hub FS access. Prefer `library/YYYY-MM-DD-<slug>.md` plus a manifest entry (id, title, path, source).',
    '- Nightly housekeeping: `NIGHTLY.md`',
    '- Factory reset (SHTF): `scripts/factory-reset.sh`',
    '- Product agent mailboxes: `agents/<slug>/inbox`, `agents/<slug>/outbox`',
    '- Architecture: `docs/ARCHITECTURE.md`',
    '',
  ].join('\n');
}

function ensureHubRuntimePrompt(hub) {
  const start = Date.now();
  ensureDir(hubPromptDir(hub));
  const file = hubRuntimePromptFile(hub);
  fs.writeFileSync(file, `${deriveHubRuntimePrompt(hub)}\n`);
  if (!fs.existsSync(hubSessionFile(hub))) resetHubSession(hub, { name: 'Main' });

  logLatency(hub, 'ensure_hub_runtime_prompt', (Date.now() - start) / 1000, {
    prompt_file: file
  });
  return file;
}

function pathExists(p) {
  try {
    fs.lstatSync(p);
    return true;
  } catch (_err) {
    return false;
  }
}

function ensureSymlink(link, target) {
  if (!pathExists(target)) return false;
  try {
    if (pathExists(link)) {
      const st = fs.lstatSync(link);
      if (st.isSymbolicLink()) {
        const current = fs.readlinkSync(link);
        if (path.resolve(path.dirname(link), current) === path.resolve(target)) return true;
        fs.unlinkSync(link);
      } else {
        return true; // leave non-symlink alone
      }
    }
    fs.symlinkSync(target, link);
    return true;
  } catch (_err) {
    return false;
  }
}

/**
 * Sandbox cwd for hub CLI launches: operational tree without root AGENT.md
 * so workspace project-instruction inject does not re-run §0 "detect built".
 */
function ensureHubRuntimeCwd(hub) {
  const cwd = hubRuntimeCwd(hub);
  ensureDir(cwd);
  const links = [
    'inbox',
    'outbox',
    'journal',
    'agents',
    'user',
    'company',
    'knowledge-stack',
    'library',
    'logs',
    'scripts',
    'templates',
    'docs',
    'registry.json',
    'cli.json',
    'NIGHTLY.md',
    'WEEKLY.md',
  ];
  for (const name of links) {
    ensureSymlink(path.join(cwd, name), path.join(hub, name));
  }
  // .bizagent → real app dir (session, prompts, locks)
  ensureSymlink(path.join(cwd, '.bizagent'), appDir(hub));
  // Explicitly do NOT link AGENT.md / AGENTS.md — that is the isolation point.
  for (const deny of ['AGENT.md', 'AGENTS.md', 'agent.md', 'agents.md']) {
    const p = path.join(cwd, deny);
    try {
      if (pathExists(p) && fs.lstatSync(p).isSymbolicLink()) fs.unlinkSync(p);
    } catch (_err) {
      /* ignore */
    }
  }
  return cwd;
}

function clip(text, max) {
  const s = String(text || '');
  if (s.length <= max) return s;
  return `${s.slice(0, max - 20)}\n\n…[truncated ${s.length - max + 20} chars]`;
}

function listPendingInboxFiles(hub) {
  const inboxDir = path.join(hub, 'inbox');
  try {
    return fs.readdirSync(inboxDir)
      .filter((f) => f.endsWith('.md') && !f.startsWith('.'))
      .sort()
      .map((f) => path.join(inboxDir, f));
  } catch (_err) {
    return [];
  }
}

function parseConversationId(text) {
  const match = String(text || '').match(/^conversation_id:\s*(.+?)\s*$/m);
  return match ? match[1].trim() : '';
}

function parseFrom(text) {
  const match = String(text || '').match(/^from:\s*(.+?)\s*$/m);
  return match ? match[1].trim() : '';
}

function parseTo(text) {
  const match = String(text || '').match(/^to:\s*(.+?)\s*$/m);
  return match ? match[1].trim() : '';
}

/**
 * Build an ephemeral turn prompt: slim system + pending mail + session pointer/excerpt.
 * Written under .bizagent/prompts/turns/; caller deletes after CLI exit.
 */
function buildHubTurnPrompt(hub) {
  const start = Date.now();
  ensureHubRuntimePrompt(hub);
  ensureDir(hubTurnsDir(hub));
  const hubAbs = path.resolve(hub);
  // Resolve acting user from pending console mail (enterprise isolation).
  let actingUserId = null;
  if (isActiveEnterprise()) {
    const hooks = getActiveEnterpriseHooks();
    if (typeof hooks.resolveActingUserId === 'function') {
      try { actingUserId = hooks.resolveActingUserId(hub, {}) || null; } catch (_e) { /* ignore */ }
    }
    if (!actingUserId) {
      for (const file of listPendingInboxFiles(hub)) {
        try {
          const body = fs.readFileSync(file, 'utf8');
          const m = body.match(/^user_id:\s*(.+?)\s*$/m);
          if (m) { actingUserId = m[1].trim(); break; }
        } catch (_e) { /* ignore */ }
      }
    }
  }
  const sessionPath = hubSessionFile(hub, actingUserId);
  const sessionRel = path.relative(hub, sessionPath);
  let sessionBody = '';
  try {
    sessionBody = fs.readFileSync(sessionPath, 'utf8');
  } catch (_err) {
    sessionBody = '_No session file yet._';
  }
  const pending = listPendingInboxFiles(hub);
  const conversationIds = [];
  const mailBlocks = pending.map((file) => {
    let body = '';
    try {
      body = fs.readFileSync(file, 'utf8');
    } catch (_err) {
      body = `_unreadable: ${file}_`;
    }
    const cid = parseConversationId(body);
    if (cid) conversationIds.push(cid);
    return [
      `### ${path.basename(file)}`,
      '',
      '```markdown',
      clip(body, MAX_TURN_MAIL_CHARS),
      '```',
      '',
    ].join('\n');
  });

  // FIFO: first pending inbox message with a conversation_id wins (matches dispatch).
  const convId = conversationIds.length
    ? conversationIds[0]
    : '';

  // ALWAYS-WARM: conversation_id is guaranteed by dispatcher.getHubConversationId()
  // If somehow missing, fail fast rather than cold-launch
  if (!convId) {
    throw new Error('hub-turn-prompt: conversation_id is required (warm-launch guarantee violated)');
  }

  // Lazy require avoids circular load (conversations → hub-memory → hub-turn-safety).
  const safety = require('./hub-turn-safety');
  const reservedBodyAbs = safety.prepareReservedReplyBody(hub, convId);

  const turnId = `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
  const turnFile = path.join(hubTurnsDir(hub), `hub-${turnId}.md`);

  logLatency(hub, 'build_hub_turn_prompt', (Date.now() - start) / 1000, {
    turn_id: turnId,
    pending_mail_count: pending.length,
    has_conversation_id: !!convId,
    has_reserved_body: !!reservedBodyAbs
  });

  // ALWAYS-WARM: Single code path — reserved body file is mandatory
  const deliveryBlock = [
    '### Operator reply delivery (MANDATORY)',
    '',
    'Stdout is **not** shown to the operator. Free-form `outbox/` files are **banned**.',
    '',
    `**conversation_id:** \`${convId}\``,
    '',
    '**Reserved body file:** write **only the final markdown body** (no YAML) to:',
    '',
    '```text',
    reservedBodyAbs,
    '```',
    '',
    'Use your file write/edit tool. Overwrite the file with the complete operator-visible reply. The control plane adds frontmatter and routes it.',
    '',
    '**Alternative — write-message helper (if file write fails):**',
    '',
    '```bash',
    actingUserId
      ? `scripts/write-message.sh --to user --from hub --subject "console reply" --conversation-id "${convId}" --user-id "${actingUserId}" --body "Your reply here."`
      : `scripts/write-message.sh --to user --from hub --subject "console reply" --conversation-id "${convId}" --body "Your reply here."`,
    '```',
    '',
    actingUserId
      ? `When writing hub→user mail, always set user_id: ${actingUserId} and conversation_id: ${convId}.`
      : 'Success = reserved body file non-empty **or** write-message wrote hub→user outbox with this conversation_id.',
    actingUserId
      ? 'Success = reserved body file non-empty **or** write-message wrote hub→user outbox with this conversation_id and user_id.'
      : '',
    '',
  ].filter((line) => line !== undefined).join('\n');

  const enterpriseCtx = applyHubTurnContext(hub, {
    conversationId: convId,
    user_id: actingUserId,
    pendingCount: pending.length,
  });

  const content = [
    '# Hub turn prompt (ephemeral)',
    '',
    'Control plane injected this file at launch. Prefer it over rediscovering context with tools.',
    '',
    '## Standing system prompt',
    '',
    deriveHubRuntimePrompt(hub).trim(),
    '',
    enterpriseCtx ? '## Enterprise seat context\n\n' + enterpriseCtx.trim() + '\n' : '',
    '## This turn',
    '',
    `- Hub absolute path: \`${hubAbs}\``,
    `- conversation_id: \`${convId}\``,
    actingUserId ? `- Acting user_id: \`${actingUserId}\`` : '',
    `- RESERVED_REPLY_BODY: \`${reservedBodyAbs}\``,
    `- Session file (read-only, already compacted by CP): \`${sessionRel}\``,
    `- Pending inbox files: ${pending.length}`,
    '',
    deliveryBlock,
    '### Order',
    '1. Read **Pending mail** and **Session excerpt** below (already inlined — avoid tool-reads unless needed).',
    '2. Deliver operator-visible text via reserved body file or `scripts/write-message.sh` (never free-form outbox; never stdout-only).',
    '3. Archive each handled inbox message to `inbox/archive/`.',
    '4. Do not implement product work; do not edit hub machinery unless the operator explicitly asked; do not run setup; do not rewrite session memory.',
    '',
    '## Pending mail',
    '',
    mailBlocks.length ? mailBlocks.join('\n') : '_No pending inbox mail._',
    '',
    '## Session excerpt (CP-compacted; do not rewrite)',
    '',
    '```markdown',
    clip(sessionBody, MAX_TURN_SESSION_CHARS),
    '```',
    '',
  ].join('\n');

  fs.writeFileSync(turnFile, content);
  return turnFile;
}

function listAgentPendingInboxFiles(hub, slug) {
  const inboxDir = path.join(hub, 'agents', slug, 'inbox');
  try {
    return fs.readdirSync(inboxDir)
      .filter((f) => f.endsWith('.md') && !f.startsWith('.'))
      .sort()
      .map((f) => path.join(inboxDir, f));
  } catch (_err) {
    return [];
  }
}

/**
 * Light product-agent turn prompt (Phase 2): standing dispatch text + pending
 * inbox bodies inlined so the agent need not tool-list/read inbox first.
 * Still memoryless across dispatches — injection is per-launch only.
 * Caller deletes the turn file after CLI exit.
 */
function buildAgentTurnPrompt(hub, slug) {
  ensureDir(hubTurnsDir(hub));
  const hubAbs = path.resolve(hub);
  const agentMd = path.join('agents', slug, 'agent.md');
  const dispatchPath = path.join(hub, 'agents', slug, '.dispatch.md');
  let standing = '';
  try {
    standing = fs.readFileSync(dispatchPath, 'utf8').trim();
  } catch (_err) {
    standing = [
      `You are the '${slug}' agent. Read ${agentMd} for your role, scope, and projects.`,
      `Process every message in agents/${slug}/inbox and ignore archive/.`,
      `Write replies to agents/${slug}/outbox; archive each handled message immediately.`,
    ].join('\n');
  }

  const pending = listAgentPendingInboxFiles(hub, slug);
  const subjects = [];
  const mailBlocks = pending.map((file) => {
    let body = '';
    try {
      body = fs.readFileSync(file, 'utf8');
    } catch (_err) {
      body = `_unreadable: ${file}_`;
    }
    const subj = String(body).match(/^subject:\s*(.+?)\s*$/m);
    if (subj) subjects.push(subj[1].trim());
    return [
      `### ${path.basename(file)}`,
      '',
      '```markdown',
      clip(body, MAX_TURN_MAIL_CHARS),
      '```',
      '',
    ].join('\n');
  });

  const turnId = `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
  const turnFile = path.join(hubTurnsDir(hub), `agent-${slug}-${turnId}.md`);
  const subjectHint = subjects.length ? subjects.join('; ') : '(none)';

  const content = [
    `# Agent turn prompt (ephemeral) — ${slug}`,
    '',
    'Control plane injected this file at launch. Prefer **Pending mail** below over listing the inbox with tools.',
    'You still run memoryless across dispatches: only this turn is injected.',
    '',
    '## Standing dispatch instructions',
    '',
    standing,
    '',
    '## This turn',
    '',
    `- Hub absolute path: \`${hubAbs}\``,
    `- Agent slug: \`${slug}\``,
    `- Role/scope file: \`${agentMd}\` (open if you need product details not in the mail)`,
    `- Inbox (real files to archive after work): \`agents/${slug}/inbox/\``,
    `- Outbox: \`agents/${slug}/outbox/\``,
    `- Pending subjects: ${subjectHint}`,
    `- Pending inbox files: ${pending.length}`,
    '',
    '### Order',
    '1. Act on **Pending mail** (bodies inlined below). Archive the real files under `agents/' + slug + '/inbox/` after each is done.',
    '2. Write reply messages to `agents/' + slug + '/outbox/` (`to: hub` unless directed otherwise).',
    '3. Before changing project code: read that project\'s `sitemap.md` (Active Work / Known Issues) and recent `.agent/journal/` — skip deep project reads for pure status/ack subjects when mail alone answers.',
    '4. Do not create a worktree unless the dispatch asks or the checkout is unsafe.',
    '',
    '## Pending mail',
    '',
    mailBlocks.length ? mailBlocks.join('\n') : '_No pending inbox mail._',
    '',
  ].join('\n');

  fs.writeFileSync(turnFile, content);
  return turnFile;
}

function excerpt(content) {
  const text = String(content || '').replace(/\s+/g, ' ').trim();
  if (text.length <= MAX_EXCERPT_CHARS) return text;
  return `${text.slice(0, MAX_EXCERPT_CHARS - 3)}...`;
}

function roleLabel(role, hub) {
  if (role === 'user') {
    // Lazy require avoids load cycles with conversations → hub-memory.
    try {
      return require('./profile').userDisplayName(hub);
    } catch (_err) {
      return 'You';
    }
  }
  return 'Hub';
}

function renderSummary(existingSummary, olderTurns, hub) {
  const lines = [];
  if (existingSummary) lines.push(existingSummary.trim());
  if (olderTurns.length === 0 && lines.length === 0) return '- No older turns summarized yet.';
  const shown = olderTurns.slice(-MAX_SUMMARY_BULLETS);
  const omitted = olderTurns.length - shown.length;
  if (olderTurns.length > 0) lines.push(`- ${olderTurns.length} older turn(s) compressed into summary form.`);
  if (omitted > 0) lines.push(`- ${omitted} earliest summarized turn(s) omitted from this compact runtime file.`);
  for (const turn of shown) {
    lines.push(`- ${roleLabel(turn.role, hub)}: ${excerpt(turn.content)}`);
  }
  return lines.join('\n');
}

function renderRecentTurns(recentTurns, hub) {
  if (recentTurns.length === 0) return '_No recent turns yet._';
  return recentTurns.map((turn) => [
    `### ${roleLabel(turn.role, hub)} - ${turn.created_at || 'unknown time'}`,
    '',
    '```text',
    String(turn.content || '').trim(),
    '```',
  ].join('\n')).join('\n\n');
}

function renderHubSession(conversation, hub) {
  const messages = Array.isArray(conversation.messages) ? conversation.messages : [];
  const recent = messages.slice(-MAX_RECENT_TURNS);
  const older = messages.slice(0, Math.max(0, messages.length - recent.length));
  return [
    '# Hub Session Memory',
    '',
    `Conversation: ${conversation.name || 'Conversation'}`,
    `Started: ${conversation.created_at || 'unknown'}`,
    `Updated: ${conversation.updated_at || new Date().toISOString()}`,
    '',
    '## Rolling Summary',
    '',
    renderSummary(conversation.summary, older, hub),
    '',
    '## Recent Turns',
    '',
    renderRecentTurns(recent, hub),
    '',
  ].join('\n');
}

function resetHubSession(hub, conversation, sessionOrUserId) {
  ensureDir(appDir(hub));
  const uid =
    sessionOrUserId ||
    (conversation && conversation.user_id) ||
    null;
  const file = hubSessionFile(hub, uid);
  const conv = {
    name: (conversation && conversation.name) || 'Conversation',
    created_at: (conversation && conversation.created_at) || new Date().toISOString(),
    updated_at: (conversation && conversation.updated_at) || new Date().toISOString(),
    messages: [],
  };
  fs.writeFileSync(file, renderHubSession(conv, hub));
  return file;
}

function compactHubSession(hub, conversation, sessionOrUserId) {
  ensureDir(appDir(hub));
  const uid =
    sessionOrUserId ||
    (conversation && conversation.user_id) ||
    null;
  const file = hubSessionFile(hub, uid);
  fs.writeFileSync(file, renderHubSession(conversation || {}, hub));
  return file;
}

module.exports = {
  buildAgentTurnPrompt,
  buildHubTurnPrompt,
  compactHubSession,
  deriveHubRuntimePrompt,
  ensureHubRuntimeCwd,
  ensureHubRuntimePrompt,
  extractAgentSections,
  hubRuntimeCwd,
  hubRuntimePromptFile,
  hubSessionFile,
  hubTurnsDir,
  listAgentPendingInboxFiles,
  listPendingInboxFiles,
  resetHubSession,
};
