const fs = require('fs');
const path = require('path');
const { appDir, ensureDir } = require('./config');
const { logEvent, logLatency } = require('./log');

const MAX_RECENT_TURNS = 12;
const MAX_SUMMARY_BULLETS = 16;
const MAX_EXCERPT_CHARS = 220;
/** Cap inline session body in turn prompts (full session still on disk). */
const MAX_TURN_SESSION_CHARS = 6000;
/** Cap each pending mail body embedded in the turn prompt. */
const MAX_TURN_MAIL_CHARS = 8000;

function hubPromptDir(hub) {
  return path.join(appDir(hub), 'prompts');
}

function hubRuntimePromptFile(hub) {
  return path.join(hubPromptDir(hub), 'hub.md');
}

function hubTurnsDir(hub) {
  return path.join(hubPromptDir(hub), 'turns');
}

function hubSessionFile(hub) {
  return path.join(appDir(hub), 'hub-session.md');
}

function hubRuntimeCwd(hub) {
  return path.join(appDir(hub), 'runtime-cwd');
}

function extractAgentSections(agentText) {
  const start = agentText.search(/^## § 3\b/m);
  const end = agentText.search(/^## § 5\b/m);
  if (start === -1) throw new Error('AGENT.md is missing § 3');
  return agentText.slice(start, end === -1 ? agentText.length : end).trim();
}

/**
 * Slim always-on hub runtime prompt (Phase 1).
 * Fat detail (Knowledge Stack, journal schemas, Claude hook, nightly) is
 * on-demand via paths — open only when the turn needs it.
 * Session compaction is owned by the control plane; the LLM must not rewrite
 * hub-session.md.
 */
function deriveHubRuntimePrompt(hub) {
  const sessionRel = path.relative(hub, hubSessionFile(hub));
  const hubAbs = path.resolve(hub);
  return [
    '# BizAgent Hub Runtime Prompt',
    '',
    'Generated always-on runtime prompt (slim). Do not edit this file directly;',
    'edit control-plane/lib/hub-memory.js deriveHubRuntimePrompt or AGENT.md and regenerate.',
    '',
    '## Identity',
    '',
    'You are the **Products Team Lead** (PTL). You report to the operator (CEO).',
    'Hub-and-spoke: this repo is the hub; each product has one agent owning one or more project repos.',
    '`registry.json` is the source of truth. Use each product\'s `agent_name` when speaking to the operator;',
    'use slugs only in message file headers (`from:`, `to:`).',
    '',
    '## What is a "product"? (teach this when operators are confused)',
    '',
    'A **product** is anything that requires you to **gather** information or parts, **build** something,',
    'and ultimately **distribute** that result to others — not only software.',
    'Examples: a resume to an employer, a report to a manager, an app to the App Store, a campaign, a paper.',
    'If it matches gather → build → distribute, it can be managed as a BizAgent product (own agent, journal, sitemap).',
    'BizAgent is a product-development operating system — not "smart Google search" and not only a coding assistant.',
    '',
    '## System state (always true on runtime launches)',
    '',
    `- Hub root (absolute): \`${hubAbs}\``,
    '- The system is **BUILT**. `registry.json` exists. **Never** run setup/interview or §0 "detect state".',
    '- Do **not** re-read root `AGENT.md` for setup. Operational rules are in this prompt.',
    '',
    '## Non-negotiable limits',
    '',
    '1. You **NEVER** write code, edit project files, update sitemaps, or write journal entries for any product.',
    '2. You **NEVER** do work that belongs to a product agent — even if small or faster yourself.',
    '3. Operator task → identify owning agent by name → message their inbox → wait for reply → report back.',
    '4. If you touch anything inside a project repo or `agents/<slug>/` for product work: stop, undo, delegate.',
    '',
    '## Brevity',
    '',
    'Replies to the operator default to **two sentences or less**. Longer only when the work requires it.',
    'Messages to product agents: only what the recipient needs to act — no preamble, recap, or signoff.',
    '',
    '## Channel rules (non-negotiable)',
    '',
    '- **Stdout is debug only.** Nothing you print is shown to the operator. Never "answer" in chat text alone.',
    '- **Operator-visible text** must go through a CP-owned write path (below). Free-form `outbox/*.md` creation is **banned** — wrong filename, missing `conversation_id`, or wrong `to:` silently drops the reply.',
    '- Product-agent mail (to a slug) also uses the write-message helper — same rule.',
    '- When an agent→hub message arrives **with a conversation_id** (completion notification), you **must** write a short user-visible summary for the operator using the reserved body or write-message path. Do not silently archive it.',
    '',
    '## This-turn order (outbox-first)',
    '',
    '1. **Answer first** via the mandatory write path (see Message delivery). Success = that write returns OK / the reserved body file is non-empty.',
    '2. **Then housekeep:** archive handled `inbox/*.md` into `inbox/archive/` immediately after acting on each.',
    '3. Session memory is **CP-owned** (see Runtime Memory). Do not rewrite or compress it.',
    '4. Only then: optional journal `[Maintenance]` / `[Company]` bullets if warranted.',
    '',
    '## Message delivery (mandatory write path)',
    '',
    '### Operator / console reply (`to: user`)',
    '',
    'When this turn has a `conversation_id`, prefer **one** of:',
    '',
    '1. **Reserved body file** (preferred when the turn prompt gives `RESERVED_REPLY_BODY`): write **only the markdown body** (no YAML frontmatter) to that absolute path with your file tool. The control plane wraps frontmatter and routes it.',
    '2. **write-message helper:**',
    '   ```bash',
    '   scripts/write-message.sh --to user --from hub --subject "short subject" \\',
    '     --conversation-id "<id from this turn>" --body "Your reply here."',
    '   # or: echo "body" | scripts/write-message.sh --to user --from hub --subject "..." --conversation-id "..."',
    '   ```',
    '',
    'Do **not** hand-write files under `outbox/`. Do **not** invent a `conversation_id`.',
    '',
    '### Product-agent mail',
    '',
    '```bash',
    'scripts/write-message.sh --to <slug> --from hub --subject "short subject" --body "..."',
    '```',
    '',
    '**Interim messages** only for unbounded delays (dispatch, URL fetch): brief write-message first, full reply second, same `conversation_id`. Skip interims for quick synthesis.',
    '',
    '## Runtime Memory (CP-owned)',
    '',
    `\`${sessionRel}\` is current session memory (rolling summary + recent turns). The control plane already compacted it.`,
    '**Read-only for you.** Do not compress, rewrite, or "keep compact" this file — the CP owns that.',
    'Use the **Pending mail** and **Session** sections of the turn prompt when provided; open the session file only if the turn prompt lacks what you need.',
    '',
    '## On-demand references (open only if this turn needs them)',
    '',
    '- Full setup/ops manual: `AGENT.md` (never for §0 detect-built on a live hub)',
    '- Knowledge Stack / weekly refresh: `WEEKLY.md`, `company/`, `knowledge-stack/`',
    '- Nightly housekeeping: `NIGHTLY.md`',
    '- Product agent mailboxes: `agents/<slug>/inbox`, `agents/<slug>/outbox`',
    '- Architecture: `docs/ARCHITECTURE.md`',
    '',
  ].join('\n');
}

function ensureHubRuntimePrompt(hub) {
  const start = Date.now();
  ensureDir(hubPromptDir(hub));
  const file = hubRuntimePromptFile(hub);
  fs.writeFileSync(file, `${deriveHubRuntimePrompt(hub)}\n`);
  if (!fs.existsSync(hubSessionFile(hub))) resetHubSession(hub, { name: 'Main' });

  logLatency(hub, 'ensure_hub_runtime_prompt', (Date.now() - start) / 1000, {
    prompt_file: file
  });
  return file;
}

function pathExists(p) {
  try {
    fs.lstatSync(p);
    return true;
  } catch (_err) {
    return false;
  }
}

function ensureSymlink(link, target) {
  if (!pathExists(target)) return false;
  try {
    if (pathExists(link)) {
      const st = fs.lstatSync(link);
      if (st.isSymbolicLink()) {
        const current = fs.readlinkSync(link);
        if (path.resolve(path.dirname(link), current) === path.resolve(target)) return true;
        fs.unlinkSync(link);
      } else {
        return true; // leave non-symlink alone
      }
    }
    fs.symlinkSync(target, link);
    return true;
  } catch (_err) {
    return false;
  }
}

/**
 * Sandbox cwd for hub CLI launches: operational tree without root AGENT.md
 * so workspace project-instruction inject does not re-run §0 "detect built".
 */
function ensureHubRuntimeCwd(hub) {
  const cwd = hubRuntimeCwd(hub);
  ensureDir(cwd);
  const links = [
    'inbox',
    'outbox',
    'journal',
    'agents',
    'user',
    'company',
    'knowledge-stack',
    'logs',
    'scripts',
    'templates',
    'docs',
    'registry.json',
    'cli.json',
    'NIGHTLY.md',
    'WEEKLY.md',
  ];
  for (const name of links) {
    ensureSymlink(path.join(cwd, name), path.join(hub, name));
  }
  // .bizagent → real app dir (session, prompts, locks)
  ensureSymlink(path.join(cwd, '.bizagent'), appDir(hub));
  // Explicitly do NOT link AGENT.md / AGENTS.md — that is the isolation point.
  for (const deny of ['AGENT.md', 'AGENTS.md', 'agent.md', 'agents.md']) {
    const p = path.join(cwd, deny);
    try {
      if (pathExists(p) && fs.lstatSync(p).isSymbolicLink()) fs.unlinkSync(p);
    } catch (_err) {
      /* ignore */
    }
  }
  return cwd;
}

function clip(text, max) {
  const s = String(text || '');
  if (s.length <= max) return s;
  return `${s.slice(0, max - 20)}\n\n…[truncated ${s.length - max + 20} chars]`;
}

function listPendingInboxFiles(hub) {
  const inboxDir = path.join(hub, 'inbox');
  try {
    return fs.readdirSync(inboxDir)
      .filter((f) => f.endsWith('.md') && !f.startsWith('.'))
      .sort()
      .map((f) => path.join(inboxDir, f));
  } catch (_err) {
    return [];
  }
}

function parseConversationId(text) {
  const match = String(text || '').match(/^conversation_id:\s*(.+?)\s*$/m);
  return match ? match[1].trim() : '';
}

/**
 * Build an ephemeral turn prompt: slim system + pending mail + session pointer/excerpt.
 * Written under .bizagent/prompts/turns/; caller deletes after CLI exit.
 */
function buildHubTurnPrompt(hub) {
  const start = Date.now();
  ensureHubRuntimePrompt(hub);
  ensureDir(hubTurnsDir(hub));
  const hubAbs = path.resolve(hub);
  const sessionPath = hubSessionFile(hub);
  const sessionRel = path.relative(hub, sessionPath);
  let sessionBody = '';
  try {
    sessionBody = fs.readFileSync(sessionPath, 'utf8');
  } catch (_err) {
    sessionBody = '_No session file yet._';
  }
  const pending = listPendingInboxFiles(hub);
  const conversationIds = [];
  const mailBlocks = pending.map((file) => {
    let body = '';
    try {
      body = fs.readFileSync(file, 'utf8');
    } catch (_err) {
      body = `_unreadable: ${file}_`;
    }
    const cid = parseConversationId(body);
    if (cid) conversationIds.push(cid);
    return [
      `### ${path.basename(file)}`,
      '',
      '```markdown',
      clip(body, MAX_TURN_MAIL_CHARS),
      '```',
      '',
    ].join('\n');
  });

  const convId = conversationIds.length
    ? conversationIds[conversationIds.length - 1]
    : '';
  const convLine = convId || '(none in pending mail)';

  // Lazy require avoids circular load (conversations → hub-memory → hub-turn-safety).
  let reservedBodyAbs = '';
  if (convId) {
    const safety = require('./hub-turn-safety');
    reservedBodyAbs = safety.prepareReservedReplyBody(hub, convId);
  }

  const turnId = `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
  const turnFile = path.join(hubTurnsDir(hub), `hub-${turnId}.md`);

  logLatency(hub, 'build_hub_turn_prompt', (Date.now() - start) / 1000, {
    turn_id: turnId,
    pending_mail_count: pending.length,
    has_conversation_id: !!convId,
    has_reserved_body: !!reservedBodyAbs
  });

  const deliveryBlock = convId
    ? [
      '### Operator reply delivery (MANDATORY — pick one)',
      '',
      'Stdout is **not** shown to the operator. Free-form `outbox/` files are **banned**.',
      '',
      `**conversation_id:** \`${convId}\``,
      '',
      '**Option A — reserved body file (preferred):** write **only the final markdown body** (no YAML) to:',
      '',
      '```text',
      reservedBodyAbs,
      '```',
      '',
      'Use your file write/edit tool. Overwrite the file with the complete operator-visible reply. The control plane adds frontmatter and routes it.',
      '',
      '**Option B — write-message helper:**',
      '',
      '```bash',
      `scripts/write-message.sh --to user --from hub --subject "console reply" --conversation-id "${convId}" --body "Your reply here."`,
      '```',
      '',
      'Success = reserved body file non-empty **or** write-message wrote hub→user outbox with this conversation_id.',
      '',
    ].join('\n')
    : [
      '### Operator reply delivery',
      '',
      'No console `conversation_id` on this turn (agent→hub or maintenance). Still use',
      '`scripts/write-message.sh` for any mail you send. Stdout is not a delivery channel.',
      '',
    ].join('\n');

  const content = [
    '# Hub turn prompt (ephemeral)',
    '',
    'Control plane injected this file at launch. Prefer it over rediscovering context with tools.',
    '',
    '## Standing system prompt',
    '',
    deriveHubRuntimePrompt(hub).trim(),
    '',
    '## This turn',
    '',
    `- Hub absolute path: \`${hubAbs}\``,
    `- conversation_id: \`${convLine}\``,
    reservedBodyAbs ? `- RESERVED_REPLY_BODY: \`${reservedBodyAbs}\`` : '',
    `- Session file (read-only, already compacted by CP): \`${sessionRel}\``,
    `- Pending inbox files: ${pending.length}`,
    '',
    deliveryBlock,
    '### Order',
    '1. Read **Pending mail** and **Session excerpt** below (already inlined — avoid tool-reads unless needed).',
    '2. Deliver operator-visible text via reserved body file or `scripts/write-message.sh` (never free-form outbox; never stdout-only).',
    '3. Archive each handled inbox message to `inbox/archive/`.',
    '4. Do not implement product work; do not run setup; do not rewrite session memory.',
    '',
    '## Pending mail',
    '',
    mailBlocks.length ? mailBlocks.join('\n') : '_No pending inbox mail._',
    '',
    '## Session excerpt (CP-compacted; do not rewrite)',
    '',
    '```markdown',
    clip(sessionBody, MAX_TURN_SESSION_CHARS),
    '```',
    '',
  ].filter((line) => line !== undefined).join('\n');

  fs.writeFileSync(turnFile, content);
  return turnFile;
}

function listAgentPendingInboxFiles(hub, slug) {
  const inboxDir = path.join(hub, 'agents', slug, 'inbox');
  try {
    return fs.readdirSync(inboxDir)
      .filter((f) => f.endsWith('.md') && !f.startsWith('.'))
      .sort()
      .map((f) => path.join(inboxDir, f));
  } catch (_err) {
    return [];
  }
}

/**
 * Light product-agent turn prompt (Phase 2): standing dispatch text + pending
 * inbox bodies inlined so the agent need not tool-list/read inbox first.
 * Still memoryless across dispatches — injection is per-launch only.
 * Caller deletes the turn file after CLI exit.
 */
function buildAgentTurnPrompt(hub, slug) {
  ensureDir(hubTurnsDir(hub));
  const hubAbs = path.resolve(hub);
  const agentMd = path.join('agents', slug, 'agent.md');
  const dispatchPath = path.join(hub, 'agents', slug, '.dispatch.md');
  let standing = '';
  try {
    standing = fs.readFileSync(dispatchPath, 'utf8').trim();
  } catch (_err) {
    standing = [
      `You are the '${slug}' agent. Read ${agentMd} for your role, scope, and projects.`,
      `Process every message in agents/${slug}/inbox and ignore archive/.`,
      `Write replies to agents/${slug}/outbox; archive each handled message immediately.`,
    ].join('\n');
  }

  const pending = listAgentPendingInboxFiles(hub, slug);
  const subjects = [];
  const mailBlocks = pending.map((file) => {
    let body = '';
    try {
      body = fs.readFileSync(file, 'utf8');
    } catch (_err) {
      body = `_unreadable: ${file}_`;
    }
    const subj = String(body).match(/^subject:\s*(.+?)\s*$/m);
    if (subj) subjects.push(subj[1].trim());
    return [
      `### ${path.basename(file)}`,
      '',
      '```markdown',
      clip(body, MAX_TURN_MAIL_CHARS),
      '```',
      '',
    ].join('\n');
  });

  const turnId = `${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
  const turnFile = path.join(hubTurnsDir(hub), `agent-${slug}-${turnId}.md`);
  const subjectHint = subjects.length ? subjects.join('; ') : '(none)';

  const content = [
    `# Agent turn prompt (ephemeral) — ${slug}`,
    '',
    'Control plane injected this file at launch. Prefer **Pending mail** below over listing the inbox with tools.',
    'You still run memoryless across dispatches: only this turn is injected.',
    '',
    '## Standing dispatch instructions',
    '',
    standing,
    '',
    '## This turn',
    '',
    `- Hub absolute path: \`${hubAbs}\``,
    `- Agent slug: \`${slug}\``,
    `- Role/scope file: \`${agentMd}\` (open if you need product details not in the mail)`,
    `- Inbox (real files to archive after work): \`agents/${slug}/inbox/\``,
    `- Outbox: \`agents/${slug}/outbox/\``,
    `- Pending subjects: ${subjectHint}`,
    `- Pending inbox files: ${pending.length}`,
    '',
    '### Order',
    '1. Act on **Pending mail** (bodies inlined below). Archive the real files under `agents/' + slug + '/inbox/` after each is done.',
    '2. Write reply messages to `agents/' + slug + '/outbox/` (`to: hub` unless directed otherwise).',
    '3. Before changing project code: read that project\'s `sitemap.md` (Active Work / Known Issues) and recent `.agent/journal/` — skip deep project reads for pure status/ack subjects when mail alone answers.',
    '4. Do not create a worktree unless the dispatch asks or the checkout is unsafe.',
    '',
    '## Pending mail',
    '',
    mailBlocks.length ? mailBlocks.join('\n') : '_No pending inbox mail._',
    '',
  ].join('\n');

  fs.writeFileSync(turnFile, content);
  return turnFile;
}

function excerpt(content) {
  const text = String(content || '').replace(/\s+/g, ' ').trim();
  if (text.length <= MAX_EXCERPT_CHARS) return text;
  return `${text.slice(0, MAX_EXCERPT_CHARS - 3)}...`;
}

function roleLabel(role, hub) {
  if (role === 'user') {
    // Lazy require avoids load cycles with conversations → hub-memory.
    try {
      return require('./profile').userDisplayName(hub);
    } catch (_err) {
      return 'You';
    }
  }
  return 'Hub';
}

function renderSummary(existingSummary, olderTurns, hub) {
  const lines = [];
  if (existingSummary) lines.push(existingSummary.trim());
  if (olderTurns.length === 0 && lines.length === 0) return '- No older turns summarized yet.';
  const shown = olderTurns.slice(-MAX_SUMMARY_BULLETS);
  const omitted = olderTurns.length - shown.length;
  if (olderTurns.length > 0) lines.push(`- ${olderTurns.length} older turn(s) compressed into summary form.`);
  if (omitted > 0) lines.push(`- ${omitted} earliest summarized turn(s) omitted from this compact runtime file.`);
  for (const turn of shown) {
    lines.push(`- ${roleLabel(turn.role, hub)}: ${excerpt(turn.content)}`);
  }
  return lines.join('\n');
}

function renderRecentTurns(recentTurns, hub) {
  if (recentTurns.length === 0) return '_No recent turns yet._';
  return recentTurns.map((turn) => [
    `### ${roleLabel(turn.role, hub)} - ${turn.created_at || 'unknown time'}`,
    '',
    '```text',
    String(turn.content || '').trim(),
    '```',
  ].join('\n')).join('\n\n');
}

function renderHubSession(conversation, hub) {
  const messages = Array.isArray(conversation.messages) ? conversation.messages : [];
  const recent = messages.slice(-MAX_RECENT_TURNS);
  const older = messages.slice(0, Math.max(0, messages.length - recent.length));
  return [
    '# Hub Session Memory',
    '',
    `Conversation: ${conversation.name || 'Conversation'}`,
    `Started: ${conversation.created_at || 'unknown'}`,
    `Updated: ${conversation.updated_at || new Date().toISOString()}`,
    '',
    '## Rolling Summary',
    '',
    renderSummary(conversation.summary, older, hub),
    '',
    '## Recent Turns',
    '',
    renderRecentTurns(recent, hub),
    '',
  ].join('\n');
}

function resetHubSession(hub, conversation) {
  ensureDir(appDir(hub));
  const file = hubSessionFile(hub);
  const conv = {
    name: (conversation && conversation.name) || 'Conversation',
    created_at: (conversation && conversation.created_at) || new Date().toISOString(),
    updated_at: (conversation && conversation.updated_at) || new Date().toISOString(),
    messages: [],
  };
  fs.writeFileSync(file, renderHubSession(conv, hub));
  return file;
}

function compactHubSession(hub, conversation) {
  ensureDir(appDir(hub));
  const file = hubSessionFile(hub);
  fs.writeFileSync(file, renderHubSession(conversation || {}, hub));
  return file;
}

module.exports = {
  buildAgentTurnPrompt,
  buildHubTurnPrompt,
  compactHubSession,
  deriveHubRuntimePrompt,
  ensureHubRuntimeCwd,
  ensureHubRuntimePrompt,
  extractAgentSections,
  hubRuntimeCwd,
  hubRuntimePromptFile,
  hubSessionFile,
  hubTurnsDir,
  listAgentPendingInboxFiles,
  listPendingInboxFiles,
  resetHubSession,
};
